[package]
name = "workspaces-rs"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "workspaces"
path = "src/main.rs"

[dependencies]
clap = { version = "4.4.10", features = ["derive"] }
directories = "0.4.0"
dialoguer = { version = "0.11.0", features = ["fuzzy-select"] }
colored = "2.1.0"
