[package]
name = "workspaces"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.4.10", features = ["derive"] }
fuzzy-search = "0.1.0"
directories = "0.4.0"
ruscii = "0.4.0"
