[package]
name = "workspaces-rs"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "workspaces"
path = "src/main.rs"

[dependencies]
clap = { version = "4.4.10", features = ["derive"] }
fuzzy-search = "0.1.0"
directories = "0.4.0"
ruscii = "0.4.0"
